### ISSUE TITLE
docker command not found on registry

### ISSUE THREAD

**Issue by Madko** [fleeto/kubeadm-offline-installer#5]
Hi,

first of all thank you for this playbook. This is really helpful.
But when I try to run it, I've got this error:
```
TASK [registry : Loading image] ***********************************************************************************************************************************************************************************
fatal: [192.168.2.69]: FAILED! => {"changed": true, "cmd": "docker load -i /tmp/registry-2.6.2.tar.gz", "delta": "0:00:00.005853", "end": "2018-04-11 16:30:34.610014", "msg": "non-zero return code", "rc": 127, "start": "2018-04-11 16:30:34.604161", "stderr": "/bin/sh: docker: command not found", "stderr_lines": ["/bin/sh: docker: command not found"], "stdout": "", "stdout_lines": []}
```
Is that normal ? Should the registry be configured before running this playbook ?

Best regards,
Edouard

**Comment by Madko** [comment]
If I add the docker role to the registry host group in cluster.yml, I get an other error a bit later, but this time it's kubeadm command that is missing on master0. So I'm certainly doing something wrong.

Here is my group_vars/all:
```

main_version: "v1.10.0"
etcd_version: "3.1.12"
coredns_version: "1.0.6"
pause_version: "3.1"
kubeadm_version: "v1.10.0"
kubeadm_init_options: " --pod-network-cidr=172.16.0.0/16 --feature-gates CoreDNS=true"

# Proxy Related
proxy_host: "192.168.2.127"
proxy_port: "3128"
proxy_env:
  - http_proxy: "http://192.168.2.127:3128"
    https_proxy: "http://192.168.2.127:3128"
docker_proxy: 1

remove_search_in_resolve: 1

cert_local_path: /tmp/cert
registry_cert_path: /etc/registry/pki
ca_output_file: "ca"
ca_input_file: "ca.csr.json"
cert_ca_cert_name: "{{ ca_output_file }}.pem"
cert_ca_key_name: "{{ ca_output_file }}-key.pem"

deploy_package:
  - calico
  - pause
registry_port: 5000
yaml_root: /root/deployed_yaml

```
